name: Credo

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Credo

    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
      CI: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          version-type: strict
          version-file: .tool-versions

      - name: Restore dependencies cache
        id: dependency-cache
        uses: actions/cache@v5
        with:
          path: |
                _build
                deps
          key: ${{ github.ref }}-credo-v1-${{ hashFiles('**/mix.lock') }}-${{ hashFiles('./.tool-versions') }}
          restore-keys: ${{ github.ref }}-credo-v1-${{ hashFiles('**/mix.lock') }}-${{ hashFiles('./.tool-versions') }}

      - name: Remove app/* from _build/{test,prod,dev}/lib # This forces just our apps to recompile every time
        run: rm -rf _build/{test,prod,dev}/lib/$(ls apps)

      - name: Install dependencies & compile
        run: mix do deps.get, compile

      - name: Run Credo
        run: mix credo
